#!/usr/bin/env bash

set -euo pipefail

versions=()
while IFS='' read -r version ; do
  versions+=("${version}")
done < ./versions

previous_version="${versions[0]}"

prefix="rails "
for version in "${versions[@]}" ; do
  if [[ "${version}" = "${previous_version}" ]] ; then
    continue
  fi

  diff \
    --ignore-space-change \
    --minimal \
    --recursive \
    --unidirectional-new-file \
    --unified \
    "${prefix}${previous_version}" "${prefix}${version}" \
    > "${previous_version} to ${version}.diff" \
    || true
  previous_version="${version}"
done
