#!/usr/bin/env bash

set -euo pipefail

versions=()
while IFS='' read -r version ; do
  versions+=("${version}")
done < ./versions

prefix="rails "
for version in "${versions[@]}" ; do
  echo >&2
  # * Rails 5.2 is not compatible with Ruby 3
  # * Rails 6 throws `Psych::AliasesNotEnabled` in the `webpacker` gem when
  #   using `psych` v4 that ships with Ruby 3.1
  if (( $(echo "${version} < 7.0" | bc -l) )) ; then
    # @see https://github.com/sidekiq/sidekiq/issues/5140
    # @see https://github.com/rails/rails/issues/41074
    preferred_ruby_version="2.7.8"
  else
    preferred_ruby_version="3.2.6"
  fi
  echo "${preferred_ruby_version}" > "./.ruby-version"
  echo "INFO: Using Ruby ${preferred_ruby_version}" >&2

  bundle update \
    --bundler

  bundler_major_version="$(
    bundler \
      --version \
    | grep \
      --extended-regexp \
      --only-matching \
      '[[:digit:]]' \
    | head \
      -1
  )"

  if [[ "${version}" = "4"* ]] && [[ "${bundler_major_version}" = "2" ]] ; then
    echo "INFO: Skipping Rails ${version} because it doesn't work with Bundler v2" >&2
    continue
  fi

  echo "INFO: Installing Rails ${version}..." >&2

  rm \
    -rf \
    -- "./${prefix}${version}"

  cat \
    -- Gemfile.template \
  | sed "s/RAILS_VERSION/${version}/" \
    > Gemfile

  bundle check \
  || bundle install \
    --path vendor/bundle

  flags=
  # Work around bootsnap issue with Rails 6.0, 6.1, 7.0: `rails new`
  # post-install fails with `cannot load such file -- bootsnap/setup`.
  if (( $(echo "${version} >= 6.0" | bc -l) )) ; then
    flags="--skip-bootsnap"
  fi

  # Work around dependency issues with Rails 6.0.
  if [[ "${version}" = "6.0" ]] ; then
    # @see https://stackoverflow.com/q/47605810
    bundle add \
      webpacker \
      --version="~> 4.0"

    # @see https://stackoverflow.com/q/38663706
    bundle add \
      listen \
      --version="~> 3.2"
  fi

  # Work around dependency issues with Rails 7.0.
  if [[ "${version}" = "7.0" ]] ; then
    flags="--skip-javascript"
  fi

  # Work around dependency issues with Rails 7.1.
  if [[ "${version}" = "7.1" ]] ; then
    bundle add \
      stringio \
      --version="~> 3.0"
  fi

  bundle exec \
    rails new \
      "${prefix}${version}" "${flags}"

  # Remove auto-initialized git repository.
  rm -rf \
    -- "${prefix}${version}"/.git

  echo "INFO: Installed Rails ${version}" >&2
  echo
done
